language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  
script:
  - coverage run --source MKLpy tests\unit_tests.py

after_success:
  - coveralls
