site_name: MKLpy
repo_url: https://github.com/IvanoLauriola/MKLpy
repo_name: "GitHub"
site_description: "Code documenation for MKLpy"
site_author: "Lauriola Ivano"

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex
  - codehilite:
      linenums: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css


#material journal readthedocs
theme: 
  name: material
  palette:
    primary: 'blue'
    accent: 'indigo'
  titles_only: true


nav:
  - Home: index.md
  - About: about.md
  #- FAQ: faq.md
  - DOCUMENTATION:
    - Work in progress...: 404.md
    #- Algorithms: algorithms.md
    #- Generators: generators.md
    #- Callbacks: callbacks.md
    #- Scheduler: scheduler.md
  - TUTORIALS: 
    - Get started: examples/examples_loading.md
    - Kernels computation: examples/examples_kernels.md
    - Evaluating a kernel : examples/examples_evaluation.md
    - Efficient generators: examples/examples_generators.md
    - Training   : examples/examples_training.md
  - PROJECTS:
    - KerNET: examples/proj_kernet.md
  


