site_name: MKLpy
repo_url: https://github.com/IvanoLauriola/MKLpy
repo_name: "GitHub"
site_description: "Code documenation for MKLpy"
site_author: "Lauriola Ivano"

theme: 
  name: readthedocs
  palette:
    primary: 'red'
    accent: 'indigo'

#readthedocs material

nav:
  - Home: index.md
  - About: about.md
  - FAQ: faq.md
  - <span style="color:#2E64FE">Documenation</span>:
    - Algorithms: algorithms.md
    - Generators: generators.md
    - Callbacks: callbacks.md
    - Scheduler: scheduler.md
  - <span style="color:#2E64FE">examples</span>: 
    - Basic usage: examples_basic.md
    - Training   : examples_training.md
  


markdown_extensions:
  - admonition
