site_name: MKLpy
repo_url: https://github.com/IvanoLauriola/MKLpy
repo_name: "GitHub"
site_description: "Code documenation for MKLpy"
site_author: "Lauriola Ivano"

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - codehilite:
      linenums: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css


#material journal readthedocs
theme: 
  name: material
  palette:
    primary: 'blue'
    accent: 'indigo'
  titles_only: true
  #features:
  #  - tabs


nav:
  - Home: index.md
  - About: about.md
  #- FAQ: faq.md
  - TUTORIALS: 
    - Get started: examples/examples_loading.md
    - Kernels computation: examples/examples_kernels.md
    - Evaluating a kernel : examples/examples_evaluation.md
    - Efficient generators: examples/examples_generators.md
    - Training   : examples/examples_training.md
    - Model selection   : examples/examples_modelselection.md
  - API reference:
    - Algorithms:
      - MKL: API/MKL.md
      - AverageMKL: API/AverageMKL.md
      - EasyMKL: API/EasyMKL.md
      - PWMK: API/PWMK.md
      - FHeuristic: API/FHeuristic.md
      - CKA: API/CKA.md
      - GRAM: API/GRAM.md
      - R-MKL: API/RMKL.md
      - MEMO: API/MEMO.md
    #- Callbacks: API/callbacks.md
  - Contributing: developers/contributing.md
  - PROJECTS:
    - KerNET: projects/proj_kernet.md
    #- Extreme Spectrum Machine: examples/proj_esm.md
  


